#page title
page_title                                : Growth – baby & child growth charts        # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 446639811                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : # https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Growth                                    # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Baby & child growth charts                  # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : The app to record your child's measurements and track them on standard growth charts with percentiles.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Clafou Ltd
your_link                                 : https://www.clafou.com
your_city                                 : Dublin
email_address                             : support@clafou.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : clafou
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
sections:
- heading: Answers your questions
  features                                  :

    - title                                 : Is my child growing at the right pace?
      description                           : The reference curves on your chart let you see typical progress.
      fontawesome_icon_name                 : question
      
    - title                                 : What are my baby's percentiles?
      description                           : See the percentile for weight, height and head circumference.
      fontawesome_icon_name                 : question

    - title                                 : What is my child's BMI?
      description                           : Normal BMI bands change with a child's age. The app calculates BMI scores and percentile.
      fontawesome_icon_name                 : question

- heading: Includes the most authoritative growth charts with percentiles
  features                                  :

    - title                                 : World Health Organization (WHO)
      description                           : Ideal for breastfed babies and children around the world.
      fontawesome_icon_name                 : clipboard
      
    - title                                 : US Centers for Disease Control and Prevention (CDC)
      description                           : Best for formula-fed babies and North American children.
      fontawesome_icon_name                 : clipboard
      
    - title                                 : Preterm baby charts (Fenton)
      description                           : Dedicated chart for premature babies.
      fontawesome_icon_name                 : clipboard
      
- heading: Easily maintain growth records
  features                                  :

    - title                                 : Ready when you are
      description                           : No account or password to remember. No Internet connection required.
      fontawesome_icon_name                 : star
      
    - title                                 : Fast, flexible input
      description                           : Speedy entry with on-the-fly unit conversion and autocorrect.
      fontawesome_icon_name                 : star

    - title                                 : Your data, yours alone
      description                           : Easily export (CSV, PDF, JPEG). Choose your storage – local or on iCloud Drive, Dropbox or other for private back up and sync.
      fontawesome_icon_name                 : star


- heading: For every parent
  features                                  :

    - title                                 : "All ages: babies, toddlers, children, teens"
      description                           : Keep tracking for years, from newborns all the way to adulthood. No subscription, use it forever! On the App Store since 2010.
      fontawesome_icon_name                 : heart
      
    - title                                 : Premie-friendly
      description                           : Dedicated preterm charts using gestational age for newborns. Corrected age support for the ongoing monitoring of premature babies.
      fontawesome_icon_name                 : heart

    - title                                 : Compare siblings
      description                           : Display multiple children together to compare their growth at the same age.
      fontawesome_icon_name                 : heart



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#000000"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#1d63ea"
cover_overlay_transparency                : 0.0

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#000000"
app_price_color                           : "#000000"
app_description_color                     : "#000000"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown

### From GitHub Pages
# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from  

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://growthchart.app" # the base hostname & protocol for your site, e.g. http://example.com
