#page title
page_title                                : Growth – baby & child growth charts        # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 446639811                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : # https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Growth                                    # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : baby & child growth charts                  # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Track your child's growth

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Clafou Ltd
your_link                                 : https://www.clafou.com
your_city                                 : Dublin
email_address                             : support@clafou.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : clafou
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : All ages
    description                           : Includes head circumference and weight-for-length references for newborns and babies, and BMI for older children and teens.
    fontawesome_icon_name                 : signal
    
  - title                                 : Official growth charts
    description                           : Choose the official WHO and CDC templates used by pediatricians or custom charts automatically tailored to your child's lifespan.
    fontawesome_icon_name                 : clipboard

  - title                                 : Whole family
    description                           : View siblings together to compare their growth as they age. Give the other parent access via iCloud Drive, and purchase once via Family Sharing.
    fontawesome_icon_name                 : user-friends

  - title                                 : Premie-friendly
    description                           : Dedicated preterm charts for newborns and corrected age support for ongoing monitoring of premature babies.
    fontawesome_icon_name                 : heart

  - title                                 : Your data, yours alone
    description                           : Secure on-device storage. Manage your storage using files. Store it on iCloud Drive, Dropbox or other for private back up and sync.
    fontawesome_icon_name                 : folder

  - title                                 : Independent and caring
    description                           : On the App Store for 10 years and joined by other apps to grow into a family business. Has never included ads and never collected your data.
    fontawesome_icon_name                 : star

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#000000"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#1d63ea"
cover_overlay_transparency                : 0.0

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#000000"
app_price_color                           : "#000000"
app_description_color                     : "#000000"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown

### From GitHub Pages
# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from  

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com